baseURL = "https://upstart.solutions/"
languageCode = "en-us"
title = "UpStart Productions"
pagination.pagerSize = 12
enableRobotsTXT = true
canonifyURLs = true
relativeURLs = true
theme = ""
mainSections = ["posts"]

[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"

# Clean URLs (Hugo default, but explicit here)
disablePathToLower = false
uglyURLs = false

# Output formats for Blowfish
[outputFormats]
  [outputFormats.HTML]
    mediaType = "text/html"
    isHTML = true
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "index"
    isHTML = false
  [outputFormats.JSON]
    mediaType = "application/json"
    isHTML = false

# Goldmark: allow HTML in Markdown (for data-* and inline HTML)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

# Clean URL structure
[permalinks]
  posts = "/:slug/"

# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 10

  [[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 20

  [[menu.main]]
    name = "Services"
    pageRef = "/services"
    weight = 30

  [[menu.main]]
    name = "Portfolio"
    pageRef = "/portfolio"
    weight = 40

  [[menu.main]]
    name = "Nepho"
    pageRef = "/nepho"
    weight = 50

  [[menu.main]]
    name = "Demo"
    pageRef = "/demo"
    weight = 55

  [[menu.main]]
    name = "Showcase"
    pageRef = "/showcase"
    weight = 56

  [[menu.main]]
    name = "Contact"
    pageRef = "/contact"
    weight = 60
