[params.author]
name     = "UpStart Productions"
headline = "Creative tech for nonprofits & innovators"
bio      = "Websites, apps, and workflow tools—privacy-first and people-first."

[params.social]
github = "upstart-productions"
twitter = "upstart_prod"
linkedin = "upstart-productions"
email = "hello@upstart.solutions"
