[params]
  colorScheme = "auto"
  defaultAppearance = "dark"
  autoSwitchAppearance = false
  
  # Site metadata
  description = "UpStart Productions - Creative solutions and innovative technology"
  
  # Homepage layout
  homepage.layout = "hero"

  # Brand palette
  primaryColor = "#0ea5e9"   # cyan-500 (buttons, links, accents)
  secondaryColor = "#14b8a6" # teal-500 (hover states, highlights)
  neutralColor = "#1e293b"   # slate-800 (cards, section backgrounds)

  # Optional: fine-tune text
  textColor = "#f1f5f9"      # slate-100 (main body text)
  headingColor = "#ffffff"   # pure white for titles
  
  # Article settings
  article.showDate = true
  article.showDateUpdated = false
  article.showAuthor = false
  article.showWordCount = false
  article.showReadingTime = false
  article.showEdit = false
  article.showViews = false
  article.showLikes = false
  article.showTaxonomies = false
  article.showPagination = true
  article.invertPagination = false
  article.showToC = false
  article.tocOpen = false
  
  # List settings
  list.showBreadcrumbs = false
  list.showSummary = false
  list.showViews = false
  list.showLikes = false
  list.showTableOfContents = false
  list.showCards = true
  list.groupByYear = false
  list.cardView = false
  list.cardViewScreenWidth = false
  
  # Site settings
  site.showCopyright = true
  site.showThemeAttribution = false
  site.showAppearanceSwitcher = true
  site.showScrollToTop = true
