[params]
  colorScheme = "auto"
  defaultAppearance = "dark"
  autoSwitchAppearance = false
  
  # Site metadata
  description = "UpStart Productions - Creative solutions and innovative technology"

  # Brand palette
  primaryColor = "#0ea5e9"   # cyan-500 (buttons, links, accents)
  secondaryColor = "#14b8a6" # teal-500 (hover states, highlights)
  neutralColor = "#1e293b"   # slate-800 (cards, section backgrounds)

  # Optional: fine-tune text
  textColor = "#f1f5f9"      # slate-100 (main body text)
  headingColor = "#ffffff"   # pure white for titles
  
  # Homepage settings - use Blowfish's native hero layout
  [params.homepage]
    layout = "hero"
    homepageImage = "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80"
    showRecent = false
    showMoreLink = false
  
  # Header settings - make it more visual
  [params.header]
    layout = "fixed-fill-blur"

  # Article settings - enable all visual features
  article.showDate = true
  article.showDateUpdated = false
  article.showAuthor = false
  article.showWordCount = true
  article.showReadingTime = true
  article.showEdit = false
  article.showViews = false
  article.showLikes = false
  article.showTaxonomies = true
  article.showPagination = true
  article.invertPagination = false
  article.showToC = true
  article.tocOpen = false
  article.showHero = true
  article.heroStyle = "background"
  
  # List settings
  list.showBreadcrumbs = false
  list.showSummary = true
  list.showViews = false
  list.showLikes = false
  list.showTableOfContents = false
  list.showCards = true
  list.groupByYear = false
  list.cardView = true
  list.cardViewScreenWidth = false
  
  # Site settings
  site.showCopyright = true
  site.showThemeAttribution = false
  site.showAppearanceSwitcher = true
  site.showScrollToTop = true
